#[derive(Debug)]
pub(crate) enum OptimulaConceptConst {
    CONCEPT_TIMESHEETS_PLAN = 1001,
    CONCEPT_TIMESHEETS_WORK = 1002,
    CONCEPT_TIMEACTUAL_WORK = 1003,
    CONCEPT_PAYMENT_BASIS   = 2001,
    CONCEPT_PAYMENT_HOURS   = 2002,
    CONCEPT_PAYMENT_FIXED   = 2003,
    CONCEPT_OPTIMUS_BASIS   = 2011,
    CONCEPT_OPTIMUS_HOURS   = 2012,
    CONCEPT_OPTIMUS_FIXED   = 2013,
    CONCEPT_OPTIMUS_NETTO   = 2014,
    CONCEPT_REDUCED_BASIS   = 2021,
    CONCEPT_REDUCED_HOURS   = 2022,
    CONCEPT_REDUCED_FIXED   = 2023,
    CONCEPT_REDUCED_NETTO   = 2024,
    CONCEPT_AGRWORK_HOURS   = 2031,
    CONCEPT_AGRTASK_HOURS   = 2032,
    CONCEPT_ALLOWCE_MFULL   = 3001,
    CONCEPT_ALLOWCE_HFULL   = 3002,
    CONCEPT_ALLOWCE_HOURS   = 3003,
    CONCEPT_ALLOWCE_DAILY   = 3004,
    CONCEPT_ALLDOWN_DAILY   = 3005,
    CONCEPT_OFFWORK_HOURS   = 3011,
    CONCEPT_OFFTASK_HOURS   = 3012,
    CONCEPT_OFFSETS_HFULL   = 3013,
    CONCEPT_OFFSETS_HOURS   = 3014,
    CONCEPT_OFFSETS_DAILY   = 3015,
    CONCEPT_OFFDOWN_DAILY   = 3016,
    CONCEPT_SETTLEM_TARGETS = 4001,
    CONCEPT_SETTLEM_TARNETT = 4002,
    CONCEPT_SETTLEM_AGRWORK = 4003,
    CONCEPT_SETTLEM_AGRTASK = 4004,
    CONCEPT_SETTLEM_ALLOWCE = 4005,
    CONCEPT_SETTLEM_ALLNETT = 4006,
    CONCEPT_SETTLEM_OFFWORK = 4011,
    CONCEPT_SETTLEM_OFFTASK = 4012,
    CONCEPT_SETTLEM_OFFSETS = 4013,
    CONCEPT_SETTLEM_RESULTS = 4014,
    CONCEPT_SETTLEM_RESNETT = 4015,
    CONCEPT_INCOMES_TAXFREE = 5001,
    CONCEPT_INCOMES_TAXBASE = 5002,
    CONCEPT_INCOMES_TAXWINS = 5003,
    CONCEPT_INCOMES_SUMMARY = 5004,
}

#[allow(dead_code)]
impl OptimulaConceptConst {
    pub(crate) fn name_of_concept(item: i32) -> String {
        let article: OptimulaConceptConst = unsafe { std::mem::transmute(item as i32) };
        format!("{:?}", article)
    }
}

